In [1]:
import pandas as pd

In [4]:
bac= pd.read_csv("C:/Users/amema/OneDrive/Desktop/data/bac.csv")

In [6]:
from sklearn.model_selection import train_test_split

train_data, test_data = train_test_split(bac, test_size=0.2, random_state=42)

In [7]:
train_data.head()

,Nom,"Serie,x",GroupeAnonymat,LieuNaissance,Centre,Etablissement,moyeneGeneral,Decision,Note1,Note2,...,Note7,Note8,Willaya,moughataa,DateNaissance,ID,Today2021,Age,prenom,sexe
20967,Walad Haboub Nakh,SN,SN10,Las Palmas,College Teyarett 1,Ghabess Teyaret,3.539062,Ajourné,1.75,1.250,...,1.75,17.0,Nouakchott 1 (Nord),TEYARETT,2001-10-24,ID_22987,2021-10-03,19.0,Walad,F
10432,Saidou Abou Ba,SN,SN11,Rosso,Ecole Satara Rosso,Lycée Rosso,5.796875,Ajourné,5.25,4.750,...,1.00,16.0,Trarza,ROSSO,2000-01-17,ID_12169,2021-10-03,21.0,Saidou,M
20464,Djeinaba Malick Ba,SN,SN07,Zoueirat,Lycée Sebkha 1,EL AWLAMA SBK,8.453125,Sessionnaire,7.50,8.500,...,6.00,18.0,Nouakchott 2 (Ouest),SEBKHA,2002-04-21,ID_29121,2021-10-03,19.0,Djeinaba,F
16758,Ahmed Babe Ahmedou Abeidallah,SN,SN09,Toujounine,Lycée Jedida,CARAVANE DU SAVAOIR Ksar,7.296875,Ajourné,9.75,7.250,...,5.25,18.5,Nouakchott 2 (Ouest),KSAR,2003-07-09,ID_26568,2021-10-03,18.0,Ahmed,M
2718,Fatma Siyid Siyid,LM,LM4,Beileguet Litam,Ecole Sidi Abdoullah-Arafat,Lycée Arafat 1,5.705645,Ajourné,3.00,8.375,...,6.75,-1.0,Nouakchott 3 (Sud),ARAFAT,1999-01-06,ID_36182,2021-10-03,22.0,Fatma,F

In [8]:
test_data.head()

,Nom,"Serie,x",GroupeAnonymat,LieuNaissance,Centre,Etablissement,moyeneGeneral,Decision,Note1,Note2,...,Note7,Note8,Willaya,moughataa,DateNaissance,ID,Today2021,Age,prenom,sexe
21709,Hawa Abdellahi Sow,SN,SN11,Riyad,Lycée El Mina 2,Candidats Libres Elmina,8.435484,Sessionnaire,10.000,9.50,...,9.750000,-1.0,Nouakchott 3 (Sud),EL MINA,1999-01-30,ID_38977,2021-10-03,22.0,Hawa,F
7700,Khawleta Mohamed Mahmoud Nejachy Sidi Abderrah...,LM,LM1,Kiffa,Lycée Kiffa 3,Lycee Kifa 1,5.379032,Ajourné,7.875,4.50,...,6.000000,-1.0,Assaba,KIFFA,2001-11-17,ID_5841,2021-10-03,19.0,Khawleta,F
2388,Hemoud Mohamed Abdellahi Mohamed Abdellahi,LM,LM1,Sani,Lycée Kiffa 3,Abdel Aziz Sy,3.650538,Ajourné,1.500,6.00,...,10.833333,-1.0,Assaba,KIFFA,1997-12-31,ID_4447,2021-10-03,21.0,Hemoud,M
6874,Aida Jibril N'Daw,SN,SN02,Nouadhibou,Lycée Nouadhibou 1,Lycée Nouadhibou 1,2.578125,Ajourné,1.375,1.25,...,1.750000,16.5,Dakhlet NDB,NOUADHIBOU,2002-03-15,ID_17245,2021-10-03,19.0,Aida,F
4469,Mahjouba Mohamed El Moctar Naji Abd El Aziz,SN,SN10,Toujounine,Lycée Naim,Lycée Naim,3.556452,Ajourné,2.000,2.25,...,8.000000,-1.0,Trarza,BOUTILIMITT,2000-07-19,ID_14524,2021-10-03,21.0,Mahjouba,F

### Logistic regression

In [9]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer

# Sélection des caractéristiques (features) et la variable cible (target)
categorical_features = ['Etablissement', 'Serie,x','Centre','Willaya', 'moughataa']
numeric_features = ['Age']
target = 'Decision'

# Concaténation des ensembles d'entraînement et de test
all_data = pd.concat([train_data[categorical_features + numeric_features], test_data[categorical_features + numeric_features]], axis=0)

# Prétraitement des variables catégorielles
cat_transformer = OneHotEncoder(handle_unknown='ignore')
cat_transformer.fit(all_data[categorical_features])

# Prétraitement de la variable numérique
num_transformer = StandardScaler()
num_transformer.fit(all_data[numeric_features])

# Création du transformateur de colonnes
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', cat_transformer, categorical_features),
        ('num', num_transformer, numeric_features)
    ])
# Encodage des variables catégorielles de l'ensemble d'entraînement
X_train_encoded = preprocessor.fit_transform(train_data[categorical_features + numeric_features])

# Séparation des données en ensembles d'entraînement et de test encodés
X_test_encoded = preprocessor.transform(test_data[categorical_features + numeric_features])
y_train = train_data[target]
# Modèle de régression logistique
model = LogisticRegression(max_iter=1000)
# Evaluation de la performance du modèle avec cross-validation
scores = cross_val_score(model, X_train_encoded, y_train, cv=5)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

# Entraînement du modèle sur l'ensemble d'entraînement complet
model.fit(X_train_encoded, y_train)
# Évaluation des performances du modèle en calculant l'exactitude (accuracy)
accuracy = model.score(X_train_encoded, y_train)
print("Accuracy:", accuracy)

# Faire la prédiction sur le nouveau jeu de données
y_pred = model.predict(X_test_encoded)
y_prob = model.predict_proba(X_test_encoded)

# Ajouter la prédiction en tant que colonne "Decision" dans le nouveau jeu de données
test_data['Decision'] = y_pred

# Ajouter la probabilité que la décision soit "Admis" dans le nouveau jeu de données
y_prob = model.predict_proba(X_test_encoded)
test_data['Predicted'] = y_prob[:,1]

data = test_data.loc[:, ['ID', 'Predicted']]

Accuracy: 0.80 (+/- 0.01)
Accuracy: 0.8031388961548522

#### Random Forest Classifier

In [13]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier



# Sélection des caractéristiques (features) et la variable cible (target)
categorical_features = ['Etablissement', 'Serie,x','Centre','Willaya', 'moughataa']
numeric_features = ['Age']
target = 'Decision'

# Concaténation des ensembles d'entraînement et de test
all_data = pd.concat([train_data[categorical_features + numeric_features], test_data[categorical_features + numeric_features]], axis=0)



# Prétraitement des variables catégorielles
cat_transformer = OneHotEncoder(handle_unknown='ignore')
cat_transformer.fit(all_data)

# Encodage # Prétraitement des variables catégorielles
cat_transformer = OneHotEncoder(handle_unknown='ignore')
cat_transformer.fit(all_data[categorical_features])

# Prétraitement de la variable numérique
num_transformer = StandardScaler()
num_transformer.fit(all_data[numeric_features])

# Création du transformateur de colonnes des variables catégorielles de l'ensemble d'entraînement
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', cat_transformer, categorical_features),
        ('num', num_transformer, numeric_features)
    ])

# Encodage des variables catégorielles de l'ensemble d'entraînement
X_train_encoded = preprocessor.fit_transform(train_data[categorical_features + numeric_features])

# Séparation des données en ensembles d'entraînement et de test encodés
X_test_encoded = preprocessor.transform(test_data[categorical_features + numeric_features])
y_train = train_data[target]

# Modèle Random Forest Classifier
model = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)

# Entraînement du modèle avec validation croisée
scores = cross_val_score(model, X_train_encoded, y_train, cv=5)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

# Entraînement du modèle sur l'ensemble d'entraînement complet
model.fit(X_train_encoded, y_train)

# Faire la prédiction sur le nouveau jeu de données
y_pred = model.predict(X_test_encoded)

# Ajouter la prédiction en tant que colonne "Decision" dans le nouveau jeu de données
test_data['Decision'] = y_pred

# Ajouter la probabilité que la décision soit "Admis" dans le nouveau jeu de données
y_prob = model.predict_proba(X_test_encoded)
test_data['Predicted'] = y_prob[:,1]

data = test_data.loc[:, ['ID', 'Predicted']]

Accuracy: 0.80 (+/- 0.00)

In [10]:
train_data.to_csv("C:/Users/amema/OneDrive/Desktop/data/train_set.csv", index=False)

In [11]:
test_data.to_csv("C:/Users/amema/OneDrive/Desktop/data/test_set.csv", index=False)